### ISSUE TITLE
Link to French behaviour

### ISSUE THREAD

**Issue by smellems** [sara-sabr/auto-evaluation-devops-self-assessment#33]
When arriving to the site with a French URL, the language switcher will still say Français.  Clicking to switch the language goes to English and button stays to Français (as it should), but the URL is not updated with the en parameter.  Switching language a second time, the language switcher is correctly updated.

## Steps to reproduce
1. Go to https://sara-sabr.github.io/auto-evaluation-devops-self-assessment/#/?lang=fr
    - Site content is French and the language button says Français
1. Click Français (language button)
    - Site goes to English, but URL is still `?lang=fr` 

## Expected behavior
- Language button should say English when site is in French
- URL should be updated with the correct language

**Comment by gcharest** [comment]
Issue is due to location of the button being loaded. Need to refactor app structure (current location of the button resides in the main.ts so it is not "reactive" to the locale on creation.

Two ways to do this could be to :
- add a function onMounted() that  triggers the button to refresh
- move the button location into the app.vue and have it display from there instead.
